# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


#[[main]]
#  name = "Experiência"
#  url = "#experiencia"
#  weight = 1

#[[main]]
#  name = "Certificados"
#  url = "#cursos"
#  weight = 2

[[main]]
  name = "Publicações"
  url = "#publicacoes"
  weight = 3

[[main]]
  name = "Seminários"
  url = "#seminarios"
  weight = 4

[[main]]
  name = "Materiais de estudo"
  url = "#projetos"
  weight = 5

[[main]]
  name = "Recomendações"
  url = "#recomendacoes"
  weight = 6

[[main]]
  name = "Contato"
  url = "#contato"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
