# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Projects"
  url = "#projects"
  weight = 1

#[[main]]
#  name = "Experience"
#  url = "#experience"
#  weight = 2

#[[main]]
#  name = "Certificates"
#  url = "#courses"
#  weight = 3

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 4

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 5

[[main]]
  name = "Recommendations"
  url = "#recommendations"
  weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
